name: sonarcloud
on: [push, pull_request]
jobs:
  sonarcloud:
    name: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: sonarcloud scan
        uses: SonarSource/sonarcloud-github-action@master
        run: |
          sudo apt install -y libboost-all-dev
          build_folder="build/debug"
          ccx_ver=${GITHUB_SHA::7}
          ccx_ver_folder=$(echo $ccx_ver | sed 's/\.//g')
          release_name=ccx-cli-ubuntu-2004-v"$ccx_ver"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake ../.. -DCMAKE_BUILD_TYPE=Release
          build-wrapper-linux-x86-64 --out-dir ../../build_wrapper_output_directory make -j2
          mkdir -p "$release_name"
          exeFiles=()
          for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          strip "${exeFiles[@]}"
          cp "${exeFiles[@]}" "$release_name/"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=artifact_path::$build_folder/$release_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}